[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Note: Add your actual environment variables in Netlify Dashboard
# Site Settings → Environment Variables:
# NEXT_PUBLIC_SUPABASE_URL = https://purgvbzgbdinporjahra.supabase.co  
# NEXT_PUBLIC_SUPABASE_ANON_KEY =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cmd2YnpnYmRpbnBvcmphaHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzg3OTksImV4cCI6MjA2MjQ1NDc5OX0.XeV0llTUVo_8EsQvdBFj6G7V_6zPf_PrbqlbM_c_i9U